### ISSUE TITLE
Necessary improvements checklist

### ISSUE THREAD

**Issue by mkavulich** [NCAR/ccpp-doc#70]
A few items did not make it in in time for the previous release, and there are some new documentation items that need updating:

 - [ ] Details about available unit conversions per (Some available here, but needs updating: https://github.com/NCAR/ccpp-framework/blob/main/scripts/conversion_tools/unit_conversion.py)
 - [ ] More detailed information about contributing code
 - [ ] Add more details to [scientific doc rules](https://ccpp-techdoc.readthedocs.io/en/latest/CompliantPhysicsParams.html#scientific-documentation-rules), especially on how to make block comments and examples of how they appear in the final documentation 
   - Example: `samfshalcnv.f` --> https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v2.2.0/sci_doc/group___s_a_m_f__shal_ga7c9c5f5be5cf7b4f28738a89a9103939.html
 - [ ] Add details on the required python environment for the CCPP framework
